springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  contextPath:
  port: 8081
spring:
  jackson:
    date-format: mobile.order.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
phone:
  available:
    url: http://localhost:8080/phonecatalog/